/*=========================================================================

  Program:   Visualization Toolkit
  Module:    vtkOnikaWriter.h

  Copyright (c) Ken Martin, Will Schroeder, Bill Lorensen
  All rights reserved.
  See Copyright.txt or http://www.kitware.com/Copyright.htm for details.

     This software is distributed WITHOUT ANY WARRANTY; without even
     the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
     PURPOSE.  See the above copyright notice for more information.

=========================================================================*/
// .NAME vtkOnikaWriter - generate scalars along a specified direction
// .SECTION Description
// vtkOnikaWriter is a filter to generate scalar values from a
// dataset.  The scalar values lie within a user specified range, and
// are generated by computing a projection of each dataset point onto
// a line. The line can be oriented arbitrarily. A typical example is
// to generate scalars based on elevation or height above a plane.

#ifndef __vtkOnikaWriter_h
#define __vtkOnikaWriter_h

#include "vtkPassThrough.h"

class VTK_EXPORT vtkOnikaWriter : public vtkPassThrough
{
public:
  static vtkOnikaWriter* New();
  vtkTypeMacro(vtkOnikaWriter, vtkPassThrough);
  void PrintSelf(ostream& os, vtkIndent indent);

protected:
  vtkOnikaWriter();
  ~vtkOnikaWriter();

private:
  vtkOnikaWriter(const vtkOnikaWriter&);  // Not implemented.
  void operator=(const vtkOnikaWriter&);  // Not implemented.
};

#endif
